carla_fps: 20
eval_freq: 1
save_freq: 10
n_waypoints: 10
yaw_noise: 0.0

infraction_lookahead: 4
infraction_weight: 100
infraction_penalty: -10.0

brain:
  main: "langprop"
  langprop:
    training: true
    batch_update_freq: 100
    replay_batch_size: 1000
    train_batch_size: 1000
    val_batch_size: 1000
    n_attempts: 5

    train_path: "langprop/expert/training/offline_dataset"
    val_path: "langprop/expert/testing/offline_dataset"

    run_config:
      n_responses: 2
      n_top_choices: 2
      max_keep: 20
      exception_score: -10.0
      forward_timeout: 5
      trackers_config:
        main:
          priority_decay_rate: 0.0

  expert:
    time_margin: 2
    dist_margin: 2
    stop_sign:
      speed_thresh: 0.1
      valid_steps: 50

distance:
  vehicle: 50
  walker: 50
  traffic_light: 75
  stop_sign: 50

sensor:
  front_only: true
  camera:
    x: -1.5
    y: 0.0
    z: 2.0
    width: 900
    height: 256
    fov: 100
  use_seg: false
#  lidar:
#    x: 0.0
#    y: 0.0
#    z: 2.5
  topdown:
    x: 0.0
    y: 0.0
    z: 100.0
    width: 500
    height: 500
    focal_length: 500   # best to have pixel per meter (focal_length / z) to be an integer value
  map:
    rgb_front: "rgb"