TAG: 'mile'
LOG_DIR: 'tensorboard_logs'

GPUS: 2
BATCHSIZE: 4
STEPS: 100000

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 8

RECEPTIVE_FIELD: 6
FUTURE_HORIZON: 6

PRETRAINED:
  PATH: ''

DATASET:
  DATAROOT: ''
