TAG: 'one_frame_baseline'
LOG_DIR: 'tensorboard_logs'

GPUS: 2
BATCHSIZE: 32
STEPS: 50000
N_WORKERS: 4

RECEPTIVE_FIELD: 1
FUTURE_HORIZON: 0

MODEL:
  TRANSITION:
    ENABLED: False

DATASET:
  DATAROOT: ''
